config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "tops#intro"
  resources :posts, only: [:new, :create, :edit, :update, :show, :destroy] do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  get 'tops/many', to: 'tops#many'
  get 'tops/intro', to: 'tops#intro'
  resources :players, only: [:index]
  resources :users, only: [:show, :edit, :update]
  resources :tops, only: [:index]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :post
end

app/models/image.rb
class Image < ApplicationRecord

  mount_uploader :image, ImageUploader
  belongs_to :product, optional: true
  
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/opponent.rb
class Opponent < ActiveHash::Base
  self.data = [
      {id: 1, name: '巨人'}, {id: 2, name: 'ヤクルト'}, {id: 3, name: '中日'},
      {id: 4, name: '阪神'}, {id: 5, name: '広島'}, {id: 6, name: '日本ハム'}, {id: 7, name: '楽天'}, {id: 8, name: '千葉ロッテ'}, {id: 9, name: '西武'}, {id: 10, name: 'オリックス'}, {id: 11, name: 'ソフトバンク'},
  ]
end

app/models/place.rb
class Place < ActiveHash::Base
  self.data = [
      {id: 1, name: '横浜スタジアム'}, {id: 2, name: '東京ドーム'}, {id: 3, name: '神宮球場'},
      {id: 4, name: 'ナゴヤドーム'}, {id: 5, name: '甲子園球場'}, {id: 6, name: 'MAZDA Zoom-Zoomスタジアム'}, {id: 7, name: '札幌ドーム'}, {id: 8, name: '楽天生命パーク'}, {id: 9, name: '西武ドーム'}, {id: 10, name: 'ZOZOマリンスタジアム'}, {id: 11, name: '京セラドーム'}, {id: 12, name: '福岡PayPayドーム'}, {id: 13, name: 'その他'},
  ]
end

app/models/player.rb
class Player < ActiveHash::Base
  self.data = [
      {id: 1, name: '今永選手'}, {id: 2, name: '上茶谷選手'}, {id: 3, name: 'ソト選手'},
      {id: 4, name: 'ロペス選手'}, {id: 5, name: 'オースティン選手'}, {id: 6, name: '神里選手'}, {id: 7, name: '佐野選手'}, {id: 8, name: '山崎選手'}, {id: 9, name: '伊藤選手'}, {id: 10, name: '柴田選手'}, {id: 11, name: '梶谷選手'}, {id: 12, name: 'パットン選手'}, 
  ]
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :images, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  accepts_nested_attributes_for :comments, allow_destroy: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :player
  belongs_to_active_hash :place
  belongs_to_active_hash :opponent


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments
  has_many :posts
  has_many :likes
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :player
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.build(like_params)
    @post = @like.post
    if @like.save
      respond_to :js
    end
  end

  def destroy
    @like = Like.find(params[:id])
    @post = @like.post
    if @like.destroy
      respond_to :js
    end
  end


  private
    def like_params
      params.permit(:post_id)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
    @post.images.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to "/tops/"
    else
      render action: :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def edit
    @post = Post.find(params[:id])
    @images = @post.images
  end

  def update
    @post = Post.find(params[:id])
    @post.update_attributes(post_params)
    redirect_to "/tops/"
  end

  def destroy
    @post = Post.find(params[:id])
    redirect_to "/tops/"
  end

  private
    def post_params
      params.require(:post).permit(:content, :place_id, :player_id, :opponent_id, images_attributes: [:image, :_destroy, :id]).merge(user_id: current_user.id)
    end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.includes(:user).order('created_at DESC').limit(5)
  end

  def many
    @posts = Post.includes(:user).order('created_at DESC')
  end

  def intro
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id)
  end


  def edit
    @user = User.find(params[:id])
  end

  def update
    @posts = Post.where(user_id: current_user.id)
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    render action: :show
  end


  private
    def user_params
      params.require(:user).permit(:name, :player_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tops/_footer.html.haml
.footer
  =link_to "Produce by okabeakihiro", "#"

app/views/tops/_header.html.haml
.header
  .header-left
    .header-left-title 
      = link_to "De活", tops_path
    .header-left-question
      = link_to tops_intro_path, method: :get do
        =icon('fas', 'question-circle', class:"header-left-question")
  - if user_signed_in?
    #ul.header-list
      %li= link_to "選手一覧", players_path
      %li= link_to "マイページ", user_path(current_user.id)
      %li= link_to "ログアウト", destroy_user_session_path, method: :delete 
  - else
    #ul.header-list
      %li= link_to "選手一覧", players_path
      %li= link_to "今日のポジ要素", "#"
      %li= link_to "ログイン", new_user_session_path
  %i#show.fa.fa-bars
  #menu
    %i#hide.fa.fa-times
    %ul
      %li= link_to "投稿する", new_post_path
      %li= link_to "マイページ", user_path(current_user.id)
      %li= link_to "公式サイト", 'https://www.baystars.co.jp/'
      %li#info-me お問い合わせ
      

app/views/tops/_many.html.haml
.top
  .top-index
  - @posts.each do |post|
    = link_to (post_path(post.id)) do
      .top-box
        .top-box-day
          = post.created_at.to_s(:datetime_jp)
        .top-box-image
          = image_tag("#{post.images.first.image}", class:'top-box-image')
        .top-box-info
          .top-box-info-content
            = post.content
          .top-box-info-player
            今日のMVP
            = post.player.name
          .top-box-info-detail
            .top-box-info-detail-place
              = post.place.name
            .top-box-info-detail-opponent
              VS
              = post.opponent.name
          .top-box-info-user
            = link_to "#", class:"top-box-info-user" do
              = post.user.name

app/views/tops/_top-modal.html.haml
.top-modal#modal
  .top-modal-show
    = link_to "詳細", "#"
  .top-modal-edit
    = link_to "編集する", "#"
  .top-modal-deelete
    = link_to "削除する", "#"



.me
  .mycontact
    .mycontact-1
      .mycontact-1-title
        ぜひご連絡お待ちしてます
      .mycontact-1-icon#batsu
        =icon('fas', 'times', class:"batsu")
    .mycontact-email
      .mycontact-email-icon
        =icon('far', 'envelope')
      .mycontact-email-text
        = link_to "email", "#"
    .mycontact-tell
      .mycontact-tell-icon
        =icon('fas', 'phone')
      .mycontact-tell-text
        = link_to "電話する", "#"

app/views/tops/_top-view.html.haml
.top
  .top-index
  - @posts.each do |post|
    = link_to (post_path(post.id)) do
      .top-box
        .top-box-day
          = post.created_at.to_s(:datetime_jp)
        .top-box-image
          = image_tag("#{post.images.first.image}", class:'top-box-image')
        .top-box-info
          .top-box-info-content
            = post.content
          .top-box-info-player
            今日のMVP
            = post.player.name
          .top-box-info-detail
            .top-box-info-detail-place
              = post.place.name
            .top-box-info-detail-opponent
              VS
              = post.opponent.name
          .top-box-info-user
            = link_to "#", class:"top-box-info-user" do
              = post.user.name
  .next-btn
    = link_to "もっと見る", tops_many_path, class:"next-btn"

app/views/tops/index.html.haml
.wapper
  = render "header"
  = render "top-view"
  = render "footer"

app/views/tops/intro.html.haml
.intro
  .intro-text
    %p De活
    %h5 とは？？
  .intro-image
    = image_tag 'sta.jpg', class: 'aside', id: 'img', size: '1440x500'
  .intro-about
    .intro-about-content
      .intro-about-content-text
        横浜DeNAベイスターズを大好きに
        %br
        なるためのサービス
      .intro-about-content-show
        %p こんなことできます！
        %ul
          %li ・試合の感想の共有
          %li ・好きな選手の登録
          %li ・Deファンとも友達になれるかも！？
          %li ・最新情報のキャッチ
      .intro-about-content-image
        .intro-about-content-image1
          = image_tag 'ou.png'
        .intro-about-content-image2
          = image_tag 'post.png', size: '300x300'
        .intro-about-content-image3
          = image_tag 'yo.png'
        .intro-about-content-image4
          = image_tag 'lo.png'
    .intro-about-btn
      = link_to "始める", tops_path, class:"intro-about-btn"
    .bar
    .footer1
      =link_to "Produce by okabeakihiro", "#"
    

app/views/tops/many.html.haml
.wapper
  = render "header"
  = render "many"
  = render "top-modal"
  = render "footer"