config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "tops#intro"
  resources :posts, only: [:new, :create, :edit, :update, :show, :destroy] do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  get 'tops/many', to: 'tops#many'
  get 'tops/intro', to: 'tops#intro'
  resources :players, only: [:index]
  resources :users, only: [:show, :edit, :update]
  resources :tops, only: [:index]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :post
end

app/models/image.rb
class Image < ApplicationRecord

  mount_uploader :image, ImageUploader
  belongs_to :product, optional: true
  
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/opponent.rb
class Opponent < ActiveHash::Base
  self.data = [
      {id: 1, name: '巨人'}, {id: 2, name: 'ヤクルト'}, {id: 3, name: '中日'},
      {id: 4, name: '阪神'}, {id: 5, name: '広島'}, {id: 6, name: '日本ハム'}, {id: 7, name: '楽天'}, {id: 8, name: '千葉ロッテ'}, {id: 9, name: '西武'}, {id: 10, name: 'オリックス'}, {id: 11, name: 'ソフトバンク'},
  ]
end

app/models/place.rb
class Place < ActiveHash::Base
  self.data = [
      {id: 1, name: '横浜スタジアム'}, {id: 2, name: '東京ドーム'}, {id: 3, name: '神宮球場'},
      {id: 4, name: 'ナゴヤドーム'}, {id: 5, name: '甲子園球場'}, {id: 6, name: 'MAZDA Zoom-Zoomスタジアム'}, {id: 7, name: '札幌ドーム'}, {id: 8, name: '楽天生命パーク'}, {id: 9, name: '西武ドーム'}, {id: 10, name: 'ZOZOマリンスタジアム'}, {id: 11, name: '京セラドーム'}, {id: 12, name: '福岡PayPayドーム'}, {id: 13, name: 'その他'},
  ]
end

app/models/player.rb
class Player < ActiveHash::Base
  self.data = [
      {id: 1, name: '今永選手'}, {id: 2, name: '上茶谷選手'}, {id: 3, name: 'ソト選手'},
      {id: 4, name: 'ロペス選手'}, {id: 5, name: 'オースティン選手'}, {id: 6, name: '神里選手'}, {id: 7, name: '佐野選手'}, {id: 8, name: '山崎選手'}, {id: 9, name: '伊藤選手'}, {id: 10, name: '柴田選手'}, {id: 11, name: '梶谷選手'}, {id: 12, name: 'パットン選手'}, 
  ]
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :images, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  accepts_nested_attributes_for :comments, allow_destroy: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :player
  belongs_to_active_hash :place
  belongs_to_active_hash :opponent


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments
  has_many :posts
  has_many :likes
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :player
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    comment = Comment.create(comment_params)
    redirect_to "/posts/#{comment.post.id}"
  end

  
  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post
    if @comment.destroy
      respond_to :js
    else
      flash[:alert] = "コメントの削除に失敗しました"
    end
  end
  

  private
    def comment_params
      params.require(:comment).permit(:comment, :post_id, :user_id).merge(user_id: current_user.id, post_id: params[:post_id])
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.build(like_params)
    @post = @like.post
    if @like.save
      respond_to :js
    end
  end

  def destroy
    @like = Like.find(params[:id])
    @post = @like.post
    if @like.destroy
      respond_to :js
    end
  end


  private
    def like_params
      params.permit(:post_id)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
    @post.images.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to "/tops/"
    else
      render action: :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def edit
    @post = Post.find(params[:id])
    @images = @post.images
  end

  def update
    @post = Post.find(params[:id])
    @post.update_attributes(post_params)
    redirect_to "/tops/"
  end

  def destroy
    @post = Post.find(params[:id])
    redirect_to "/tops/"
  end

  private
    def post_params
      params.require(:post).permit(:content, :place_id, :player_id, :opponent_id, images_attributes: [:image, :_destroy, :id]).merge(user_id: current_user.id)
    end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.includes(:user).order('created_at DESC').limit(5)
  end

  def many
    @posts = Post.includes(:user).order('created_at DESC')
  end

  def intro
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id)
  end


  def edit
    @user = User.find(params[:id])
  end

  def update
    @posts = Post.where(user_id: current_user.id)
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    render action: :show
  end


  private
    def user_params
      params.require(:user).permit(:name, :player_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/players/_player-index.html.haml
.player
  .player-box
    .player-box-number
      19
    .player-box-info
      .player-box-info-name
        山崎康晃
      .player-box-info-birth
        1992年10月2日
        14年ドラフト1位
      .player-box-info-position
        ポジション: 抑え
      .player-box-info-intro
        やすあきジャンプ
  .player-text
    順次追加予定.......

  .player-yasuaki#modal

app/views/players/index.html.haml
.wapper
  = render "tops/header"
  = render "player-index"
  = render "tops/footer"

app/views/posts/_post-create.html.haml
.post
  .post-new
  = form_with model: @post, class:"post-form", url: { action: :create }, local: true do |f|
    %label.post-new-image#box
      = f.fields_for :images do |i|
        .input-area#box
          = i.file_field :image, id: 'img-file', style: "display:none;"
      .post-new-image-icon
        =icon('fas', 'camera')
      %h1.post-new-image-text 画像を投稿
    .post-new-info
      .post-new-info-content
        = f.text_field :content, class: 'form__post__content', required: "" , placeholder: '感想など(250文字以内)'
      .post-new-info-player
        %h2 今日のMVP
        = f.collection_select :player_id, Player.all, :id, :name, {prompt: "---"}
      .post-new-info-place
        %h2 球場
        = f.collection_select :place_id, Place.all, :id, :name, {prompt: "---"}
      .post-new-info-opponent
        %h2 対戦相手
        = f.collection_select :opponent_id, Opponent.all, :id, :name, {prompt: "---"}
      .post-new-info-btn
        = f.submit "投稿する", class:"post-new-info-btn"

app/views/posts/_post-edit.html.haml
.post
  .post-new
  = form_with model: @post, class:"post-form", url: { action: :update }, local: true do |f|
    %label.post-new-image#box
      = f.fields_for :images do |i|
        .input-area#box
          = i.file_field :image, id: 'img-file', style: "display:none;"
      .post-new-image-icon
        =icon('fas', 'camera')
      %h1.post-new-image-text 画像を投稿
    .post-new-info
      .post-new-info-content
        = f.text_field :content, class: 'form__post__content', required: "" , placeholder: '感想など(250文字以内)'
      .post-new-info-player
        %h2 今日のMVP
        = f.collection_select :player_id, Player.all, :id, :name, {prompt: "---"}
      .post-new-info-place
        %h2 球場
        = f.collection_select :place_id, Place.all, :id, :name, {prompt: "---"}
      .post-new-info-opponent
        %h2 対戦相手
        = f.collection_select :opponent_id, Opponent.all, :id, :name, {prompt: "---"}
      .post-new-info-btn
        = f.submit "変更する", class:"post-new-info-btn"

app/views/posts/_post-show.html.haml
.top-index
  .top-box
    .top-box-day
      = @post.created_at.to_s(:datetime_jp)
      .top-box-image1
        = image_tag("#{@post.images.first.image}", class:'top-box-image')
    .top-box-info
      .top-box-info-content
        = @post.content
      .top-box-info-player
        今日のMVP
        = @post.player.name
      .top-box-info-detail
        .top-box-info-detail-place
          = @post.place.name
        .top-box-info-detail-opponent
          VS
          = @post.opponent.name
      - if user_signed_in? && @post.user_id == current_user.id
        .top-box-info-bottom
          .top-box-info-bottom-btn
            .top-box-info-bottom-btn-edit
              = link_to "編集する", edit_post_path(@post.id)
            .top-box-info-bottom-btn-deleta
              = link_to "削除する", post_path(@post.id), method: :delete
            .top-box-info-bottom-btn-icon
              = icon('fas', 'heart', class:"heart-icon")
          .top-box-info-bottom-user
            = link_to "#", class:"top-box-info-user" do
              = @post.user.name
      - else
        .top-box-info-bottom
          .top-box-info-bottom-user
            = link_to "#", class:"top-box-info-user" do
              = @post.user.name
.comment
  .commentArea
    = form_with model: [@post, @comment], local: true do |f|
      = f.text_area :comment, placeholder: "コメントする", rows: "2"
      %br
      = f.submit "SEND", class:"send-comment"
.comments
  %h4 <コメント一覧>
  - if @comments
    - @comments.each do |comment|
      .comments-a
        .comments-a-user
          = link_to comment.user.name, "/users/#{comment.user.id}" 
        .comments-a-comment
          = comment.comment

app/views/posts/edit.html.haml
.wapper
  = render "tops/header"
  = render "post-edit"
  = render "tops/top-modal"
  = render "tops/footer"

app/views/posts/new.html.haml
.wapper
  = render "tops/header"
  = render "post-create"
  = render "tops/top-modal"
  = render "tops/footer"

app/views/posts/show.html.haml
.wapper
  = render "tops/header"
  = render "post-show"
  = render "tops/top-modal"
  = render "tops/footer"

app/views/users/_edit-user.html.haml
.user-editPage
  .container
    = form_with model: @user, url: { action: :update }, html: { class: 'listForm' }, local: true do |f|
      - if @user.errors.any?
        %p.text-danger 名前は1～20文字以内で入力してください
      = f.label :name, class:"editName"
      %br/

      
      = f.text_field :name, class: "form-control listName1", placeholder: "UserName"
      %h1#likeplayer 好きな選手
      %br
      = f.collection_select :player_id, Player.all, :id, :name, {prompt: "---"}, class:"playeredit"

      .text-center= f.submit "変更する", class: "submitBtn1"

  

app/views/users/_show-user.html.haml
- if @user.player_id.blank?
  .top-show
    .top-show-info
      .top-show-info-name
        = @user.name
      .top-show-info-edit
        = link_to "編集する", edit_user_path
    .top-show-player
      .top-show-player-text
        好きな選手
      .top-show-player-add1
        = link_to "追加する", edit_user_path
- else
  .top-show
    .top-show-info
      .top-show-info-name
        = @user.name
      .top-show-info-edit
        = link_to "編集する", edit_user_path
    .top-show-player
      .top-show-player-text
        好きな選手
      .top-show-player-add
        = @user.player.name
%h3 投稿一覧
.userPage
  - @posts.each do |post|
    .top-box
      .top-box-day
        = post.created_at.to_s(:datetime_jp)
        .top-box-image
          = image_tag("#{post.images.first.image}", class:'top-box-image')
      .top-box-info
        .top-box-info-content
          = post.content
        .top-box-info-player
          今日のMVP
          = post.player.name
        .top-box-info-detail
          .top-box-info-detail-place
            = post.place.name
          .top-box-info-detail-opponent
            VS
            = post.opponent.name
        .top-box-info-user
          = link_to "#", class:"top-box-info-user" do
            = post.user.name

    
  

app/views/users/edit.html.haml
.wapper
  = render "tops/header"
  = render "edit-user"
  = render "tops/footer"

app/views/users/show.html.haml
.wapper
  = render "tops/header"
  = render "show-user"
  = render "tops/top-modal"
  = render "tops/footer"